version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=quest
        - RABBITMQ_DEFAULT_PASS=quest
    ports:
      - "5672:5672"
      - "15672:15672"