spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: springtestmailtest@gmail.com
    password: Cakr1905.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true