spring:
  profiles:
    active:
      - springdatajpa
      - dev
      - postgre
      - mail
      - rabbitMQ
ca:
  dbUserName: ymlAppUsername
  dbPassword: ymlAppPassword
  dbUrl: ymlAppUrl

server:
  port: 9999

