spring:
  profiles:
    active: prod

ca:
  dbUserName: ymlUsername
  dbPassword: ymlPassword
  dbUrl: ymlUrl

server:
    port: 9999



---  # --- tipi -> yeni bir yml açar gibi davranýr bu applaction.yml okur ve ekstra profile verilen yml de okur env. ona göre düzenlenir.
    # aþaðýda belirtilen gibi -dev.yml açmak yerine bir yml açma yöntemi daha
spring:
  profiles:
    prod
ca:
  dbUserName: ymlprodUsername
  dbPassword: ymlprodPassword
  dbUrl: ymlprodUrl
