spring:
    rabbitmq:
        host: localhost
        port: 15672
        username: guest
        password: guest
        template:
            exchange: firstExchange
            routing-key: firstRoutingKey
            default-receive-queue: firstStepQueue