spring:
  profiles:
    active: prod

ca:
  dbUserName: ymlUsername
  dbPassword: ymlPassword
  dbUrl: ymlUrl

server:
    port: 9999

---

spring:
  profiles:
    active: prod
ca:
  dbUserName: ymlprodUsername
  dbPassword: ymlprodPassword
  dbUrl: ymlprodUrl
